data:
  - id: welcome-announcement
    title: Welcome to the EduX demo!
    subtitle: |
      This demo showcases what the process of what onboarding student users looks like. 
      The demo contains a traditional multi-step registration form followed by a showcase of EduX custom components.
    type: callToAction
    primaryButtonTitle: Start Demo
    secondaryButtonTitle: View Website
    secondaryButtonUri: https://www.edux.ai
    imageUri: https://github.com/AhmedIbreljic/React-Demo/blob/main/src/components/icons/welcome-modal.png
