data:
  - id: welcome-announcement
    title: Welcome to the Frigade demo!
    subtitle: |
      This demo showcases some of the UI components and onboarding functionality that Frigade offers.
      The demo contains a traditional multi-step registration form followed by a showcase of Frigade experiences.
    type: callToAction
    primaryButtonTitle: Start demo
    secondaryButtonTitle: View website
    secondaryButtonUri: https://frigade.com
    imageUri: https://app.frigade.com/images/onboarding/welcome-modal.svg
